##### Service details: #####
server.port= 8811
spring.application.name=user-service
server.url= http://localhost:8811

#Client registration properties :
eureka.client.service-url.defaultZone=http://127.0.0.1:8761/eureka

#Data source (Đổi sang PostgreSQL) :
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/users}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

#Jpa/Hibernate (Đổi Dialect sang PostgreSQL) :
spring.jpa.show-sql=true
# Dùng bản này cho PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Thêm dòng này để Hibernate không tự ý đổi tên bảng
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.ddl-auto=update

##### HTTP #####
error.404.schema.details=The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable
error.406.schema.details=This request is not acceptable. Supported MIME types are application/json

# Ép service đăng ký bằng IP thay vì hostname
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}

# Error details
server.error.include-message=always
server.error.include-binding-errors=always