#Server port
server.port=8813

#Application name
spring.application.name=order-service

#Client registration properties
eureka.client.service-url.defaultZone=http://127.0.0.1:8761/eureka

#Data source
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/orders?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

#Jpa/Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true

#Redis
spring.session.redis.namespace=session
spring.session.store-type=none
spring.redis.host=${SPRING_REDIS_HOST:127.0.0.1}
spring.redis.port=${SPRING_REDIS_PORT:6379}
spring.redis.password=${SPRING_REDIS_PASSWORD:}

# Eureka Instance Config
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}