#Server port :
server.port= 8810

#Application name :
spring.application.name=product-catalog-service

#Client registration properties :
eureka.client.service-url.defaultZone=http://127.0.0.1:8761/eureka

#Data source (Đã đổi sang PostgreSQL) :
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/product_catalog}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driverClassName=org.postgresql.Driver

#Jpa/Hibernate (Đã đổi sang PostgreSQL) :
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true

# Cấu hình đăng ký Eureka
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}
eureka.instance.instance-id=${spring.application.name}:${eureka.instance.hostname}:${server.port}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Actuator config
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Error details
server.error.include-message=always
server.error.include-binding-errors=always

# Tăng giới hạn kích thước request cho JSON và Multipart (Xử lý nhiều ảnh Base64)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-http-post-size=50MB