#Server port :
server.port= 8810

#Application name :
spring.application.name=product-catalog-service

#Client registration properties :
eureka.client.service-url.defaultZone=http://127.0.0.1:8761/eureka

#Data source (Đã đổi sang MySQL) :
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/product_catalog?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

#Jpa/Hibernate (Đã đổi sang MySQL) :
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true

# Cấu hình đăng ký Eureka
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Actuator config
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Error details
server.error.include-message=always
server.error.include-binding-errors=always

# Tăng giới hạn kích thước request cho JSON và Multipart (Xử lý nhiều ảnh Base64)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-http-post-size=50MB